//******************************************************************************
//
// MIDITrail / DIKeyDef
//
// DirectInput キーコード定義
//
// Copyright (C) 2010 WADA Masashi. All Rights Reserved.
//
//******************************************************************************


//******************************************************************************
// キーコード定義
//******************************************************************************
#define DIK_A				(0)
#define DIK_S				(1)
#define DIK_D				(2)
#define DIK_F				(3)
#define DIK_H				(4)
#define DIK_G				(5)
#define DIK_Z				(6)
#define DIK_X				(7)
#define DIK_C				(8)
#define DIK_V				(9)
//							(10)
#define DIK_B				(11)
#define DIK_Q				(12)
#define DIK_W				(13)
#define DIK_E				(14)
#define DIK_R				(15)
#define DIK_Y				(16)
#define DIK_T				(17)
#define DIK_1				(18)
#define DIK_2				(19)
#define DIK_3				(20)
#define DIK_4				(21)
#define DIK_6				(22)
#define DIK_5				(23)
#define DIK_EQUALS			(24)
#define DIK_9				(25)
#define DIK_7				(26)
#define DIK_MINUS			(27)
#define DIK_8				(28)
#define DIK_0				(29)
#define DIK_RBRACKET		(30)
#define DIK_O				(31)
#define DIK_U				(32)
#define DIK_LBRACKET		(33)
#define DIK_I				(34)
#define DIK_P				(35)
#define DIK_RETURN			(36)
#define DIK_L				(37)
#define DIK_J				(38)
#define DIK_APOSTROPHE		(39)	//[']アポストロフィ
#define DIK_K				(40)
#define DIK_SEMICOLON		(41)
#define DIK_BACKSLASH		(42)
#define DIK_COMMA			(43)
#define DIK_SLASH			(44)
#define DIK_N				(45)
#define DIK_M				(46)
#define DIK_PERIOD			(47)
#define DIK_TAB				(48)
#define DIK_SPACE			(49)
#define DIK_GRAVE			(50)	//[`]アクサングラーヴ
#define DIK_DELETE			(51)
#define DIK_ENTER			(52)
#define DIK_ESCAPE			(53)
//							(54)
#define DIK_COMMAND			(55)	//Command：左右の区別なし
#define DIK_SHIFT			(56)	//Shift  ：左右の区別なし
//							(57)
#define DIK_OPTION			(58)	//Option ：左右の区別なし
#define DIK_CONTROL			(59)	//Control：左右の区別なし
//							(60)
//							(61)
//							(62)
#define DIK_FUNCTION		(63)	//fnキー
//							(64)
#define DIK_NUMPADPERIOD	(65)
//							(66)
#define DIK_NUMPADSTAR 		(67)
//							(68)
#define DIK_NUMPADPLUS 		(69)
//							(70)
#define DIK_NUMPADCLEAR		(71)
//							(72)
//							(73)
//							(74)
#define DIK_NUMPADSLASH		(75)
#define DIK_NUMPADENTER		(76)
//							(77)
#define DIK_NUMPADMINUS		(78)
//							(79)
//							(80)
#define DIK_NUMPADEQUALS	(81)
#define DIK_NUMPAD0			(82)
#define DIK_NUMPAD1			(83)
#define DIK_NUMPAD2			(84)
#define DIK_NUMPAD3			(85)
#define DIK_NUMPAD4			(86)
#define DIK_NUMPAD5			(87)
#define DIK_NUMPAD6			(88)
#define DIK_NUMPAD7			(89)
//							(90)
#define DIK_NUMPAD8			(91)
#define DIK_NUMPAD9			(92)
//							(93)
//							(94)
//							(95)
#define DIK_F5				(96)
#define DIK_F6				(97)
#define DIK_F7				(98)
#define DIK_F3				(99)
#define DIK_F8				(100)
#define DIK_F9				(101)
//							(102)
#define DIK_F11				(103)
//							(104)
#define DIK_F13				(105)
//							(106)
#define DIK_F14				(107)
//							(108)
#define DIK_F10				(109)
//							(110)
#define DIK_F12				(111)
//							(112)
#define DIK_F15				(113)
#define DIK_HELP			(114)
#define DIK_HOME			(115)
#define DIK_PGUP			(116)
//							(117)
#define DIK_F4				(118)
#define DIK_END				(119)
#define DIK_F2				(120)
#define DIK_PGDN			(121)
#define DIK_F1				(122)
#define DIK_LEFT			(123)
#define DIK_RIGHT			(124)
#define DIK_DOWN			(125)
#define DIK_UP				(126)


